# Generated by Django 4.1.3 on 2022-12-15 17:16

import demo_app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0002_alter_villaimage_model_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=demo_app.models.get_upload_path)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='demo_app.article')),
            ],
        ),
    ]
