# Generated by Django 4.1.3 on 2022-12-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0003_article_articleimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villa',
            name='rating',
            field=models.FloatField(null=True),
        ),
    ]
