# Generated by Django 4.1.3 on 2022-12-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0004_alter_villa_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
