# Generated by Django 4.1.3 on 2022-12-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0005_villa_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
