# Generated by Django 4.1.3 on 2022-12-15 18:27

import demo_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0007_customerreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(null=True, upload_to=demo_app.models.get_upload_path)),
            ],
        ),
    ]
